"""
pages/02_Client_Dashboard.py — Clean, client-facing dashboard.
Loaded via URL query param: ?dashboard_id=<id>
Shows charts and executive summary only. No raw data, no PII info.
"""

import streamlit as st
import plotly.io as pio
from utils import storage

st.set_page_config(
    page_title="Analytics Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Minimal sidebar for internal navigation ───────────────────────────────────
with st.sidebar:
    st.page_link("app.py",                      label="🏠 Upload & Analyse")
    st.page_link("pages/01_Admin_Review.py",    label="🔍 Admin Review")
    st.page_link("pages/02_Client_Dashboard.py",label="📈 Client Dashboard")

# ── Resolve dashboard_id from query params ────────────────────────────────────
query_params = st.query_params
dashboard_id = query_params.get("dashboard_id", None)

if not dashboard_id:
    # Let admin pick from approved dashboards
    st.header("📈 Client Dashboard")
    dashboards = storage.list_dashboards()
    approved = [d for d in dashboards if d.get("review_status") == "approved"]

    if not approved:
        st.info("No approved dashboards available. Complete a review in the Admin Review page first.")
        st.stop()

    label_map = {
        f"{d['filename']}  (ID: {d['dashboard_id']})": d["dashboard_id"]
        for d in approved
    }
    selected_label = st.selectbox("Select a dashboard", list(label_map.keys()))
    dashboard_id = label_map[selected_label]
    st.info(f"Shareable URL: add `?dashboard_id={dashboard_id}` to this page's URL.")

# ── Load dashboard ────────────────────────────────────────────────────────────
data = storage.load_dashboard(dashboard_id)

if data is None:
    st.error(f"Dashboard `{dashboard_id}` not found.")
    st.stop()

if data.get("review_status") not in ("approved", "pending"):
    # Rejected — don't expose to client
    st.error("This dashboard is not available.")
    st.stop()

# ── Client view ───────────────────────────────────────────────────────────────
filename     = data.get("metadata", {}).get("filename", "Dataset")
dataset_type = data.get("dataset_type", "general").title()
created_at   = data.get("created_at", "")[:10]

st.title(f"📈 {filename} — Analytics Report")
st.caption(f"Dataset type: {dataset_type}  ·  Generated: {created_at}")
st.divider()

# KPI highlights
prof = data.get("profile", {})
numeric = prof.get("numeric", {})
if numeric:
    cols = st.columns(min(len(numeric), 4))
    for i, (col_name, stats) in enumerate(list(numeric.items())[:4]):
        with cols[i]:
            st.metric(label=col_name, value=f"{stats.get('mean', 0):,.2f}", help="Mean value")

st.divider()

# Charts
st.subheader("Key Metrics & Visualisations")
charts_json = data.get("charts", {})
if charts_json:
    for title, spec in charts_json.items():
        try:
            fig = pio.from_json(spec)
            st.markdown(f"#### {title}")
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.warning(f"Could not render '{title}': {e}")
else:
    st.info("No charts available.")

st.divider()

# Executive summary (no data quality or PII details)
summary = data.get("summary", "")
if summary:
    st.subheader("Executive Summary")
    st.markdown(summary)

# KPIs
kpis = data.get("kpis", [])
if kpis:
    st.divider()
    st.subheader("Recommended KPIs")
    for i, kpi in enumerate(kpis[:6], 1):
        st.markdown(f"**{i}. {kpi['name']}** — {kpi['description']}")

st.divider()
st.caption("Report generated by Data Dashboard MVP · Powered by Claude AI")
